env:
  browser: true
  es2021: true
  node: true
  jest: true
extends:
  - 'plugin:react/recommended'
  - airbnb
  - prettier
  - prettier/react
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
rules: {
  import/prefer-default-export: off
}
