version: 2
jobs:
  build: # runs not using Workflows must have a `build` job as entry point
    working_directory: ~/fpl_next # directory where steps will run
    docker: # run the steps with Docker
      - image: circleci/node:10.16.0
    steps:
      - checkout
      - run:
          name: update-npm
          command: "sudo npm install -g npm@latest"
      - restore_cache: # restore the dependency cache
          # https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache: # save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test
      # - run: # run coverage report
      # name: code-coverage
      # command: './node_modules/.bin/nyc report --reporter=text-lcov'
      - store_artifacts: # save test results as as artifact
          # https://circleci.com/docs/2.0/artifacts/
          path: test-results.xml
          prefix: tests
      # - store_artifacts:
      #    path: coverage
      #    prefix: coverage
      - store_test_results: # https://circleci.com/docs/2.0/collect-test-data/
          path: test-results.xml
